(defun haskell-setup ()
    (make-local-variable 'tab-stop-list)
    (setq tab-stop-list (number-sequence 0 120 4))
    (setq indent-line-function 'tab-to-tab-stop)
    (setq haskell-indent-spaces 4))
(add-hook 'haskell-mode-hook 'haskell-setup)
(add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
(eval-after-load 'flycheck '(require 'flycheck-ghcmod))
(add-hook 'haskell-mode-hook 'yas-minor-mode)
